name = "medicine-reminder-api"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "KV"
id = "943a26afb8fd4103992f92c2920f21dc"
preview_id = "25fe0387c51a4c04a2abc74e1d3e241c"

[triggers]
crons = ["* * * * *"]
